baseURL = 'https://portedsecurity.github.io/'
locale = 'en-us'
title = 'Ported Security'
theme = 'PaperMod'

# GLOBAL CONFIG PARAMETERS (Must stay right beneath the site info)
[params]
    hideCredits = true

    # This configures the home page profile layout
    [params.homeInfoParams]
        Title = "Ported Security"
        Content = "Welcome to Ported Security. Time to learn!"

# TOP RIGHT NAVIGATION MENU
[[menu.main]]
    name = "All Posts"
    url = "/posts/"
    weight = 10
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20

# SOCIAL MEDIA LINKS
[[params.socialIcons]]
    name = "github"
    url = "https://github.com/portedsecurity"